apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.metadata.name }}
type: Opaque
data:
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:5432/%s" .Values.connectionstring.username .Values.database_password  .Values.connectionstring.hostname .Values.connectionstring.database  | b64enc | quote }}
#postgres://<USERNAME>:<PASSWORD>@<HOSTNAME>:5432/<DATABASE>